version: '1'
services:

  database:
    image: postgres:15.2
    container_name: db_prod
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  blockchain:
    image: j0nasz989/bsimage:latest
    container_name: blockchainsimulation
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: java -jar app.jar
    depends_on:
      - database

