version: '2.0'
services:

  databasedev:
    image: postgres:15.2
    container_name: db_dev
    ports:
      - "5432:5432"
    volumes:
      - ./dataForTesting:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  traefik:
    image: traefik:2.9
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
    volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock