version: '1'
services:

  database:
    image: postgres:14.0
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  service:
    image: bsimage:latest
    container_name: blockchainsimulation
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: java -jar app.jar
    depends_on:
      - database
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_DATASOURCE_NAME: postgres
        SPRING_SQL_INIT_MODE: always

