services:

  blockchain:
    mem_limit: 128m
    image: "j0nasz989/bsimage:latest"
    hostname: blockchain
    ports:
      - "8081:8081"
    command: sh -c 'java -jar app.jar'
    labels:
        - "traefik.http.routers.current_blockchain_1.rule=Host(`blockchain-env.eba-ufasqxv2.us-east-1.elasticbeanstalk.com`)"
  traefik:
    mem_limit: 128m
    image: "traefik:2.9"
    hostname: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock