version: '2.0'
services:

  databasedev:
    image: postgres:15.2
    container_name: db_dev
    ports:
      - "5432:5432"
    volumes:
      - ./dataForTesting:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres