services:

  database:
    image: "postgres:15.2"
    mem_limit: 128m
    hostname: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  blockchain:
    mem_limit: 128m
    image: "j0nasz989/bsimage:latest"
    hostname: blockchain
    ports:
      - "8081:8081"
    command: sh -c './wait-for-it.sh database:5432 -t 60 && java -jar app.jar'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_NAME: postgres
      SPRING_SQL_INIT_MODE: always
    labels:
        - "traefik.http.routers.blockchain-current.rule=Host(`https://capgeminiblockchain-env.eba-edn2fgm5.us-east-1.elasticbeanstalk.com`)"
  traefik:
    mem_limit: 128m
    image: "traefik:2.9"
    hostname: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock