version: '1'
services:
  blockchainsimulation:
    image: blockchainsimulation
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: java -jar app.jar
    depends_on:
      - database

  database:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres