services:

  database:
    image: "postgres:15.2"
    mem_limit: 128m
    hostname: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  blockchain:
    mem_limit: 128m
    image: "j0nasz989/bsimage:latest"
    hostname: blockchain
    ports:
      - "8080:8080"
    command: sh -c './wait-for-it.sh database:5432 -t 60 && java -jar app.jar'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_NAME: postgres
      SPRING_SQL_INIT_MODE: always