spring:
    datasource:
        url: jdbc:postgresql://host.internal.docker:5432/postgres
        username: postgres
        password: postgres
        name: postgres
    sql:
        init:
            mode: always
    jpa:
        properties:
            hibernate:
                dialect:
                    org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true