-- CREATE TABLE wallets
-- (
--     id bigint NOT NULL,
--     wallet_uuid            varchar(128)   NOT NULL,
--     user_id varchar(128)[] NOT NULL,
--     balance            int            NOT NULL,
--     PRIMARY KEY (address)
-- );

-- insert into Wallet (id, wallet_uuid, user, user_id, listOfTransactions)
-- values (1,'100', ,,ARRAY ['1', '2']),
--        (2,'200', ,,ARRAY ['3', '4']),
--        (3,'300', ,,ARRAY ['5', '6']),
--        (4,'400', ,,ARRAY ['7', '8']),
--        (5,'500', ,,ARRAY ['9', '10']);