name: Deploy To Beanstalk

on:
  push:
    branches:
      - main
      - develop-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


#      - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#      with:
#       context: .
#          push: true
#          tags: j0nasz989/bsimage:latest
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Blockchain
          environment_name: Blockchain-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          wait_for_deployment: true